Repository plone/plone.dexterity, pull requests merged in 2020-09, with the labels that each got.

#133 Removed zope.interface pin from buildout.cfg.
  buildout.cfg
Labels: 02 type: regression, 13 prio: normal, 23 status: testing

#134 Fixed missing ISiteRoot utility when running tests with Zope 5.
  news/680.bugfix
  plone/dexterity/tests/test_views.py
Labels: 02 type: regression, 13 prio: normal, 23 status: testing, 32 needs: review

#132 Removed call of listing macro in content-core view for containers.
  news/3177.bugfix
  plone/dexterity/browser/configure.zcml
  plone/dexterity/browser/containercontentcore.pt
Labels: 01 type: bug, 13 prio: normal, 24 status: ready, 32 needs: review

#135 fix to use with fixed zope.interface
  news/135.bugfix
  plone/dexterity/tests/test_fti.py
Labels: 01 type: bug, 12 prio: high, 23 status: testing
